sudo: required
services:
  - docker

before_install:
  - docker build -t josecnsilva/docker-playground -f Dockerfile.dev .

script:
  - docker run -e CI=true josecnsilva/docker-playground npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "Docker-playground"
  env: "DockerPlayground-env"
  bucket_name: "elasticbeanstalk-sa-east-1-897861518081"
  bucket_path: "docker-playground"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
