sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t josecnsilva/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true josecnsilva/react-test npm test -- --coverage

after_success:
  - docker build -t josecnsilva/complex-client ./client
  - docker build -t josecnsilva/complex-nginx ./nginx
  - docker build -t josecnsilva/complex-server ./server
  - docker build -t josecnsilva/complex-worker ./worker

# Push production images to docker hub
  - echo -n $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_ID --password-stdin
  - docker push josecnsilva/complex-client
  - docker push josecnsilva/complex-nginx
  - docker push josecnsilva/complex-server
  - docker push josecnsilva/complex-worker
