sudo: required
services:
  - docker

before_install:
  - docker build -t josecnsilva/docker-playground -f Dockerfile.dev .

script:
  - docker run -e CI=true josecnsilva/docker-playground npm run test -- --coverage
